name: Templater - GraalVM Native Image builds
on:
  push:
    tags:        
      - '*'
permissions:
  contents: write
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle execution permissions
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: nativeCompile
      
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: templater-${{ matrix.os }}
          path: build/native/nativeCompile/templater*
          
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
